version: "3.8"
services:
  text-generation-webui:
    build:
      context: ..
      dockerfile: coolify/Dockerfile
    restart: unless-stopped
    ports:
      - "${PORT:-7860}:7860"
      - "${API_PORT:-5000}:5000"
      - "${API_STREAM_PORT:-5005}:5005"
    volumes:
      - ./cache:/home/app/text-generation-webui/cache
      - ./characters:/home/app/text-generation-webui/characters
      - ./extensions:/home/app/text-generation-webui/extensions
      - ./loras:/home/app/text-generation-webui/loras
      - ./logs:/home/app/text-generation-webui/logs
      - ./models:/home/app/text-generation-webui/models
      - ./presets:/home/app/text-generation-webui/presets
      - ./prompts:/home/app/text-generation-webui/prompts
      - ./softprompts:/home/app/text-generation-webui/softprompts
      - ./training:/home/app/text-generation-webui/training
    environment:
      - EXTRA_LAUNCH_ARGS=${EXTRA_LAUNCH_ARGS:-}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 90s
